apiVersion: v1
kind: Service
metadata:
  name: productcatalog-service
  namespace: flask-app
  labels:
    app: productcatalog
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: productcatalog 
