apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: flask-app
  labels:
    app: redis
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
