apiVersion: v1
kind: Service
metadata:
  name: productcatalog-service
  namespace: flask-app
  labels:
    app: productcatalog
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: productcatalog 
(base) Samriddha Choud:productcatalog samriddha$ cat catalog-deploy.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  namespace: flask-app
spec:
  selector:
    matchLabels:
      app: productcatalog
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalog
        tier: frontend
    spec:
      containers:
      - name: productcatalog
        image: neosam01/productcatalog:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
