apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
  labels:
    app: flaskfront
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8989
    targetPort: 8989
  selector:
    app: flaskfront 
